services:
  zookeeper:
    image: bitnami/zookeeper:latest
    networks:
      - app-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    networks:
      - app-network
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    networks:
      - app-network
    stdin_open: true
    tty: true

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge